dist: trusty
language: java
jdk:
- openjdk7

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test -B; export MAVEN_RESULT=$?
  - if [ "$MAVEN_RESULT" -ne 0 ]; then exit 1; fi

after_success:
  - mvn clean test
